// ********RoostGPT********
/*
Test generated by RoostGPT for test amanGolang using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=ArticleStore_GetComments_d7c78dda64
ROOST_METHOD_SIG_HASH=ArticleStore_GetComments_af08ddd59e

FUNCTION_DEF=func (s *ArticleStore) GetComments(m *model.Article) ([ // GetComments gets coments of the article
]model.Comment, error)
```plaintext
Scenario 1: Successful Retrieval of Comments for an Existing Article

Details:
  Description: This test case checks whether the function correctly retrieves comments for an existing article when the database query succeeds.
Execution:
  Arrange: Create an article with known comments in the database.
  Act: Call the `GetComments` method with the created article.
  Assert: Verify that the returned comments match the expected comments and that no error is returned.
Validation:
  Explain the choice of assertion and the logic behind the expected result.
  The test ensures that the function can successfully retrieve comments for a valid article, which is a fundamental feature of the application.

Scenario 2: No Comments for an Existing Article

Details:
  Description: This test verifies that the function returns an empty list of comments and no error when an article exists but has no associated comments.
Execution:
  Arrange: Create an article with no associated comments in the database.
  Act: Call the `GetComments` method with the created article.
  Assert: Ensure that an empty list of comments is returned and no error is present.
Validation:
  Explain the choice of assertion and the logic behind the expected result.
  This test checks the function's behavior when an article has no comments, ensuring robustness in handling such cases.

Scenario 3: Retrieval of Comments for a Non-Existing Article

Details:
  Description: This test case ensures that the function returns an empty list of comments and no error when queried with a non-existing article.
Execution:
  Arrange: Do not create any article in the database.
  Act: Call the `GetComments` method with an article that does not exist in the database.
  Assert: Confirm that an empty list of comments is returned and no error is present.
Validation:
  Explain the choice of assertion and the logic behind the expected result.
  This test is crucial for validating that the function does not throw errors or return incorrect data when queried with invalid inputs.

Scenario 4: Database Query Error Handling

Details:
  Description: This test checks whether the function correctly handles and returns an error when the database query fails.
Execution:
  Arrange: Set up the database to return an error on the query (e.g., by causing a database connection issue).
  Act: Call the `GetComments` method with any article.
  Assert: Verify that an error is returned and the returned comments list is empty.
Validation:
  Explain the choice of assertion and the logic behind the expected result.
  This test ensures that the function behaves correctly under database error conditions, providing reliable error handling mechanisms.

Scenario 5: Author Preloading in Comments

Details:
  Description: This test verifies that the function correctly preloads the author information for each comment.
Execution:
  Arrange: Create an article with comments, each having an associated author.
  Act: Call the `GetComments` method with the created article.
  Assert: Check that each comment in the returned list has its `Author` field populated with the correct information.
Validation:
  Explain the choice of assertion and the logic behind the expected result.
  This test ensures that the function correctly retrieves related author data, which is essential for displaying comments with author information.

Scenario 6: Database Connection is Nil

Details:
  Description: This test ensures that the function handles the case where the database connection is nil.
Execution:
  Arrange: Instantiate an `ArticleStore` with a nil database connection.
  Act: Call the `GetComments` method with any article.
  Assert: Confirm that an error is returned and the returned comments list is empty.
Validation:
  Explain the choice of assertion and the logic behind the expected result.
  This test checks that the function gracefully handles cases where the database connection is not properly initialized.
```
These scenarios cover various aspects of the `GetComments` function, including normal operations, edge cases, and error handling, ensuring comprehensive testing of the function's behavior.
*/

// ********RoostGPT********

package store

import (
	"errors"
	"testing"
	"time"

	"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
	"github.com/raahii/golang-grpc-realworld-example/model"
)

func TestArticleStoreGetComments(t *testing.T) {
	tests := []struct {
		name             string
		setupMock        func(mock sqlmock.Sqlmock)
		article          *model.Article
		expectedComments []model.Comment
		expectError      bool
	}{
		{
			name: "Successful Retrieval of Comments for an Existing Article",
			setupMock: func(mock sqlmock.Sqlmock) {
				rows := sqlmock.NewRows([]string{"id", "body", "created_at", "updated_at", "article_id", "author_id", "author_username", "author_email"}).
					AddRow(1, "Great article!", time.Now(), time.Now(), 1, 1, "user1", "user1@example.com")
				mock.ExpectQuery("SELECT .* FROM \"comments\"").WillReturnRows(rows)
			},
			article: &model.Article{ID: 1},
			expectedComments: []model.Comment{
				{ID: 1, Body: "Great article!", ArticleID: 1, AuthorID: 1, Author: model.User{Username: "user1", Email: "user1@example.com"}},
			},
			expectError: false,
		},
		{
			name: "No Comments for an Existing Article",
			setupMock: func(mock sqlmock.Sqlmock) {
				rows := sqlmock.NewRows([]string{"id", "body", "created_at", "updated_at", "article_id", "author_id", "author_username", "author_email"})
				mock.ExpectQuery("SELECT .* FROM \"comments\"").WillReturnRows(rows)
			},
			article:          &model.Article{ID: 1},
			expectedComments: []model.Comment{},
			expectError:      false,
		},
		{
			name: "Retrieval of Comments for a Non-Existing Article",
			setupMock: func(mock sqlmock.Sqlmock) {
				rows := sqlmock.NewRows([]string{"id", "body", "created_at", "updated_at", "article_id", "author_id", "author_username", "author_email"})
				mock.ExpectQuery("SELECT .* FROM \"comments\"").WillReturnRows(rows)
			},
			article:          &model.Article{ID: 999},
			expectedComments: []model.Comment{},
			expectError:      false,
		},
		{
			name: "Database Query Error Handling",
			setupMock: func(mock sqlmock.Sqlmock) {
				mock.ExpectQuery("SELECT .* FROM \"comments\"").WillReturnError(errors.New("database error"))
			},
			article:          &model.Article{ID: 1},
			expectedComments: []model.Comment{},
			expectError:      true,
		},
		{
			name: "Author Preloading in Comments",
			setupMock: func(mock sqlmock.Sqlmock) {
				rows := sqlmock.NewRows([]string{"id", "body", "created_at", "updated_at", "article_id", "author_id", "author_username", "author_email"}).
					AddRow(1, "Great article!", time.Now(), time.Now(), 1, 1, "user1", "user1@example.com")
				mock.ExpectQuery("SELECT .* FROM \"comments\"").WillReturnRows(rows)
			},
			article: &model.Article{ID: 1},
			expectedComments: []model.Comment{
				{ID: 1, Body: "Great article!", ArticleID: 1, AuthorID: 1, Author: model.User{Username: "user1", Email: "user1@example.com"}},
			},
			expectError: false,
		},
		{
			name:             "Database Connection is Nil",
			setupMock:        func(mock sqlmock.Sqlmock) {},
			article:          &model.Article{ID: 1},
			expectedComments: []model.Comment{},
			expectError:      true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v", r)
					t.Fail()
				}
			}()

			db, mock, err := sqlmock.New()
			if err != nil {
				t.Fatalf("an error '%s' was not expected when opening a stub database connection", err)
			}
			defer db.Close()

			gormDB, err := gorm.Open("sqlmock", db)
			if err != nil {
				t.Fatalf("an error '%s' was not expected when opening a stub database connection", err)
			}
			defer gormDB.Close()

			tt.setupMock(mock)

			store := &ArticleStore{db: gormDB}

			comments, err := store.GetComments(tt.article)

			if tt.expectError {
				if err == nil {
					t.Errorf("expected error, but got none")
				}
			} else {
				if err != nil {
					t.Errorf("unexpected error: %v", err)
				}
			}

			if len(comments) != len(tt.expectedComments) {
				t.Errorf("expected %d comments, but got %d", len(tt.expectedComments), len(comments))
			} else {
				for i, comment := range comments {
					if comment.ArticleID != tt.expectedComments[i].ArticleID ||
						comment.AuthorID != tt.expectedComments[i].AuthorID ||
						comment.Author.Username != tt.expectedComments[i].Author.Username ||
						comment.Author.Email != tt.expectedComments[i].Author.Email {
						t.Errorf("expected comment %+v, but got %+v", tt.expectedComments[i], comment)
					}
				}
			}

			if err := mock.ExpectationsWereMet(); err != nil {
				t.Errorf("there were unfulfilled expectations: %s", err)
			}
		})
	}
}
